import { BcryptAdapter } from "../../src/config/bcrypt.adapter";

export const seedData = {
  users: [
    {
      firstName: "Isabel",
      lastName: "Cortez",
      phoneNumber: "6621002016",
      email: "isabel.cortez@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1997-07-20T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "Adrián",
      lastName: "Molina",
      phoneNumber: "6621002017",
      email: "adrian.molina@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1983-11-11T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "Roberto",
      lastName: "Silva",
      phoneNumber: "6621002018",
      email: "roberto.silva@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1986-02-14T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "Daniela",
      lastName: "Ortega",
      phoneNumber: "6621002019",
      email: "daniela.ortega@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1994-05-22T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "Carlos",
      lastName: "Reyes",
      phoneNumber: "6621002020",
      email: "carlos.reyes@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1990-08-30T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "Lucía",
      lastName: "Fernández",
      phoneNumber: "6621002021",
      email: "lucia.fernandez@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1989-03-15T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "Miguel",
      lastName: "Álvarez",
      phoneNumber: "6621002022",
      email: "miguel.alvarez@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1992-12-01T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "Sofía",
      lastName: "Gutiérrez",
      phoneNumber: "6621002023",
      email: "sofia.gutierrez@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1995-07-08T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "Andrés",
      lastName: "Romero",
      phoneNumber: "6621002024",
      email: "andres.romero@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1987-11-25T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "Julia",
      lastName: "Castro",
      phoneNumber: "6621002025",
      email: "julia.castro@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1996-04-14T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "Diego",
      lastName: "Morales",
      phoneNumber: "6621002026",
      email: "diego.morales@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1998-02-17T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "Alejandra",
      lastName: "Jiménez",
      phoneNumber: "6621172027",
      email: "alejandra.jimenez@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1984-09-30T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "Gonzalo",
      lastName: "Ruiz",
      phoneNumber: "6621182028",
      email: "gonzalo.ruiz@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1993-05-20T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "María",
      lastName: "Vega",
      phoneNumber: "6621192029",
      email: "maria.vega@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1985-12-12T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "Javier",
      lastName: "Sánchez",
      phoneNumber: "6621662030",
      email: "javier.sanchez@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1997-08-22T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "Roberto",
      lastName: "Álvarez",
      phoneNumber: "6621012029",
      email: "roberto.alvarez@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1987-09-15T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "Gabriela",
      lastName: "Fernández",
      phoneNumber: "6621402022",
      email: "gabriela.fernandez@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1990-02-20T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "Antonio",
      lastName: "Morales",
      phoneNumber: "6621402023",
      email: "antonio.morales@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1995-07-30T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "Sandra",
      lastName: "Ortega",
      phoneNumber: "6621052024",
      email: "sandra.ortega@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1992-11-12T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "David",
      lastName: "Prieto",
      phoneNumber: "6621022025",
      email: "david.prieto@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1989-03-05T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "Lucía",
      lastName: "Gil",
      phoneNumber: "6621082026",
      email: "lucia.gil@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1994-05-16T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "Manuel",
      lastName: "Vega",
      phoneNumber: "6621802027",
      email: "manuel.vega@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1996-08-24T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "Elena",
      lastName: "Herrero",
      phoneNumber: "6621702028",
      email: "elena.herrero@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1993-12-09T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "Francisco",
      lastName: "Santos",
      phoneNumber: "6621202023",
      email: "francisco.santos@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1988-04-17T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "Marta",
      lastName: "Dominguez",
      phoneNumber: "6621002030",
      email: "marta.dominguez@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1991-06-22T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "Javier",
      lastName: "Lorenzo",
      phoneNumber: "6621002031",
      email: "javier.lorenzo@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1986-01-30T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "Carmen",
      lastName: "Iglesias",
      phoneNumber: "6621002032",
      email: "carmen.iglesias@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1995-09-14T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "Carlos",
      lastName: "Gutiérrez",
      phoneNumber: "6621002033",
      email: "carlos.gutierrez@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1990-10-05T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "Patricia",
      lastName: "Ruiz",
      phoneNumber: "6621002034",
      email: "patricia.ruiz@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1987-02-19T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "Álvaro",
      lastName: "Jiménez",
      phoneNumber: "6621002035",
      email: "alvaro.jimenez@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1992-11-11T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "Beatriz",
      lastName: "Navarro",
      phoneNumber: "6621002036",
      email: "beatriz.navarro@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1997-03-25T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "Daniel",
      lastName: "Moreno",
      phoneNumber: "6621002037",
      email: "daniel.moreno@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1996-07-19T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "Irene",
      lastName: "Cano",
      phoneNumber: "6621002038",
      email: "irene.cano@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1988-05-13T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "Sergio",
      lastName: "Romero",
      phoneNumber: "6621002039",
      email: "sergio.romero@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1994-09-30T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "Clara",
      lastName: "Vidal",
      phoneNumber: "6621002040",
      email: "clara.vidal@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1995-01-22T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "Nicolás",
      lastName: "Mendez",
      phoneNumber: "6621002041",
      email: "nicolas.mendez@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1990-11-05T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "Julia",
      lastName: "Ortiz",
      phoneNumber: "6621002042",
      email: "julia.ortiz@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1986-02-17T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "Marco",
      lastName: "Serrano",
      phoneNumber: "6621002043",
      email: "marco.serrano@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1989-08-25T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "Alicia",
      lastName: "Herrera",
      phoneNumber: "6621202044",
      email: "alicia.herrera@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1993-12-03T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "Lorenzo",
      lastName: "Gimenez",
      phoneNumber: "6621002045",
      email: "lorenzo.gimenez@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1992-04-10T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "Raquel",
      lastName: "Fuentes",
      phoneNumber: "6621002046",
      email: "raquel.fuentes@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1998-06-18T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "Ángel",
      lastName: "Ibáñez",
      phoneNumber: "6621002047",
      email: "angel.ibanez@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1991-10-07T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "Carla",
      lastName: "Campos",
      phoneNumber: "6621002048",
      email: "carla.campos@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1987-07-24T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "Félix",
      lastName: "Vega",
      phoneNumber: "6621002049",
      email: "felix.vega@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1996-03-15T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
    {
      firstName: "Iris",
      lastName: "Pascual",
      phoneNumber: "6621002050",
      email: "iris.pascual@example.com",
      password: BcryptAdapter.hash("123456"),
      dateOfBirth: new Date("1999-11-09T00:00:00.000Z"),
      img: "placeholder.png",
      permissions: {
        connect: [{ id: 2 }],
      },
    },
  ],

  species: [
    { name: "Dog" },
    { name: "Cat" },
    { name: "Parrot" },
    { name: "Tortoise" },
    { name: "Ferret" },
  ],
  pets: [
    {
      name: "Buddy",
      ownerId: 2,
      speciesId: 2,
      color: "Black",
      missingAt: new Date("2023-01-01T00:00:00.000Z"),
      img: "placeholder.png",
    },
    {
      name: "Charlie",
      ownerId: 3,
      speciesId: 3,
      color: "White",
      missingAt: new Date("2023-01-02T00:00:00.000Z"),
      img: "placeholder.png",
    },
    {
      name: "Daisy",
      ownerId: 4,
      speciesId: 4,
      color: "Brown",
      missingAt: new Date("2023-01-03T00:00:00.000Z"),
      img: "placeholder.png",
    },
    {
      name: "Max",
      ownerId: 5,
      speciesId: 5,
      color: "Golden",
      missingAt: new Date("2023-01-04T00:00:00.000Z"),
      img: "placeholder.png",
    },
    {
      name: "Bella",
      ownerId: 6,
      speciesId: 2,
      color: "Black and White",
      missingAt: new Date("2023-01-05T00:00:00.000Z"),
      img: "placeholder.png",
    },
    {
      name: "Lucy",
      ownerId: 7,
      speciesId: 3,
      color: "Grey",
      missingAt: new Date("2023-01-06T00:00:00.000Z"),
      img: "placeholder.png",
    },
    {
      name: "Molly",
      ownerId: 8,
      speciesId: 4,
      color: "Spotted",
      missingAt: new Date("2023-01-07T00:00:00.000Z"),
      img: "placeholder.png",
    },
    {
      name: "Bailey",
      ownerId: 9,
      speciesId: 5,
      color: "Brown",
      missingAt: new Date("2023-01-08T00:00:00.000Z"),
      img: "placeholder.png",
    },
    {
      name: "Stella",
      ownerId: 10,
      speciesId: 2,
      color: "Cream",
      missingAt: new Date("2023-01-09T00:00:00.000Z"),
      img: "placeholder.png",
    },
    {
      name: "Lola",
      ownerId: 11,
      speciesId: 3,
      color: "Tan",
      missingAt: new Date("2023-01-10T00:00:00.000Z"),
      img: "placeholder.png",
    },
    {
      name: "Zoe",
      ownerId: 12,
      speciesId: 4,
      color: "Silver",
      missingAt: new Date("2023-01-11T00:00:00.000Z"),
      img: "placeholder.png",
    },
    {
      name: "Ruby",
      ownerId: 13,
      speciesId: 5,
      color: "Red",
      missingAt: new Date("2023-01-12T00:00:00.000Z"),
      img: "placeholder.png",
    },
    {
      name: "Penny",
      ownerId: 14,
      speciesId: 2,
      color: "Brindle",
      missingAt: new Date("2023-01-13T00:00:00.000Z"),
      img: "placeholder.png",
    },
    {
      name: "Rosie",
      ownerId: 15,
      speciesId: 3,
      color: "Pink",
      missingAt: new Date("2023-01-14T00:00:00.000Z"),
      img: "placeholder.png",
    },
    {
      name: "Maggie",
      ownerId: 16,
      speciesId: 4,
      color: "Green",
      missingAt: new Date("2023-01-15T00:00:00.000Z"),
      img: "placeholder.png",
    },
    {
      name: "Luna",
      ownerId: 2,
      speciesId: 2,
      color: "White",
      missingAt: new Date("2023-02-01T00:00:00.000Z"),
      img: "placeholder.png",
    },
    {
      name: "Oscar",
      ownerId: 3,
      speciesId: 3,
      color: "Black",
      missingAt: new Date("2023-02-02T00:00:00.000Z"),
      img: "placeholder.png",
    },
    {
      name: "Bella",
      ownerId: 4,
      speciesId: 2,
      color: "Brown",
      missingAt: new Date("2023-02-03T00:00:00.000Z"),
      img: "placeholder.png",
    },
    {
      name: "Max",
      ownerId: 5,
      speciesId: 4,
      color: "Grey",
      missingAt: new Date("2023-02-04T00:00:00.000Z"),
      img: "placeholder.png",
    },
    {
      name: "Shadow",
      ownerId: 6,
      speciesId: 2,
      color: "Black",
      missingAt: new Date("2023-02-05T00:00:00.000Z"),
      img: "placeholder.png",
    },
    {
      name: "Milo",
      ownerId: 7,
      speciesId: 3,
      color: "White",
      missingAt: new Date("2023-02-06T00:00:00.000Z"),
      img: "placeholder.png",
    },
    {
      name: "Charlie",
      ownerId: 8,
      speciesId: 4,
      color: "Brown",
      missingAt: new Date("2023-02-07T00:00:00.000Z"),
      img: "placeholder.png",
    },
    {
      name: "Bailey",
      ownerId: 9,
      speciesId: 2,
      color: "Cream",
      missingAt: new Date("2023-02-08T00:00:00.000Z"),
      img: "placeholder.png",
    },
    {
      name: "Oliver",
      ownerId: 10,
      speciesId: 3,
      color: "Golden",
      missingAt: new Date("2023-02-09T00:00:00.000Z"),
      img: "placeholder.png",
    },
    {
      name: "Toby",
      ownerId: 11,
      speciesId: 4,
      color: "Spotted",
      missingAt: new Date("2023-02-10T00:00:00.000Z"),
      img: "placeholder.png",
    },
    {
      name: "Stella",
      ownerId: 12,
      speciesId: 2,
      color: "Striped",
      missingAt: new Date("2023-02-11T00:00:00.000Z"),
      img: "placeholder.png",
    },
    {
      name: "Coco",
      ownerId: 13,
      speciesId: 3,
      color: "Tan",
      missingAt: new Date("2023-02-12T00:00:00.000Z"),
      img: "placeholder.png",
    },
    {
      name: "Ruby",
      ownerId: 14,
      speciesId: 4,
      color: "Red",
      missingAt: new Date("2023-02-13T00:00:00.000Z"),
      img: "placeholder.png",
    },
    {
      name: "Willow",
      ownerId: 15,
      speciesId: 2,
      color: "Silver",
      missingAt: new Date("2023-02-14T00:00:00.000Z"),
      img: "placeholder.png",
    },
    {
      name: "Daisy",
      ownerId: 16,
      speciesId: 3,
      color: "White and Black",
      missingAt: new Date("2023-02-15T00:00:00.000Z"),
      img: "placeholder.png",
    },
  ],
  locations: [
    { address: "123 Main St", city: "Anytown", country: "CountryA" },
    { address: "456 Elm St", city: "Otherville", country: "CountryB" },
    { address: "789 Oak St", city: "Sometown", country: "CountryC" },
    { address: "101 Pine St", city: "Elsewhere", country: "CountryD" },
    { address: "202 Maple St", city: "Thisplace", country: "CountryE" },
    { address: "303 Birch St", city: "Thatplace", country: "CountryF" },
    { address: "404 Cedar St", city: "Hereville", country: "CountryG" },
    { address: "505 Redwood St", city: "Thereville", country: "CountryH" },
    { address: "606 Willow St", city: "Everywhere", country: "CountryI" },
    { address: "707 Palm St", city: "Nowhere", country: "CountryJ" },
    { address: "808 Magnolia St", city: "Somewhere", country: "CountryK" },
    { address: "909 Cherry St", city: "Whoville", country: "CountryL" },
    { address: "1010 Apple St", city: "Howtown", country: "CountryM" },
    { address: "1111 Orange St", city: "Whyville", country: "CountryN" },
    { address: "1212 Banana St", city: "Whatcity", country: "CountryO" },
    { address: "456 Elm St", city: "Springfield", country: "USA" },
    { address: "789 Pine St", city: "Greendale", country: "USA" },
    { address: "101 Maple Ave", city: "Shelbyville", country: "USA" },
    { address: "202 Oak St", city: "Riverdale", country: "USA" },
    { address: "303 Birch Ln", city: "Centerville", country: "USA" },
    { address: "404 Cedar Rd", city: "Smallville", country: "USA" },
    { address: "505 Walnut St", city: "Metropolis", country: "USA" },
    { address: "606 Chestnut Ave", city: "Star City", country: "USA" },
    { address: "707 Aspen Pl", city: "Coast City", country: "USA" },
    { address: "808 Magnolia Blvd", city: "Gotham", country: "USA" },
    { address: "909 Redwood St", city: "Central City", country: "USA" },
    { address: "1010 Sequoia St", city: "National City", country: "USA" },
    { address: "1111 Willow St", city: "Starling City", country: "USA" },
    { address: "1313 Peachtree Ln", city: "Midway City", country: "USA" },
    { address: "1212 Cherry St", city: "Hub City", country: "USA" },
  ],
  rewards: [
    {
      amount: 100.0,
      description: "Reward for finding Buddy",
      petId: 1,
      locationId: 1,
    },
    {
      amount: 150.0,
      description: "Reward for finding Charlie",
      petId: 2,
      locationId: 2,
    },
    {
      amount: 200.0,
      description: "Reward for finding Daisy",
      petId: 3,
      locationId: 3,
    },
    {
      amount: 250.0,
      description: "Reward for finding Max",
      petId: 4,
      locationId: 4,
    },
    {
      amount: 300.0,
      description: "Reward for finding Bella",
      petId: 5,
      locationId: 5,
    },
    {
      amount: 350.0,
      description: "Reward for finding Lucy",
      petId: 6,
      locationId: 6,
    },
    {
      amount: 400.0,
      description: "Reward for finding Molly",
      petId: 7,
      locationId: 7,
    },
    {
      amount: 450.0,
      description: "Reward for finding Bailey",
      petId: 8,
      locationId: 8,
    },
    {
      amount: 500.0,
      description: "Reward for finding Stella",
      petId: 9,
      locationId: 9,
    },
    {
      amount: 550.0,
      description: "Reward for finding Lola",
      petId: 10,
      locationId: 10,
    },
    {
      amount: 600.0,
      description: "Reward for finding Zoe",
      petId: 11,
      locationId: 11,
    },
    {
      amount: 650.0,
      description: "Reward for finding Ruby",
      petId: 12,
      locationId: 12,
    },
    {
      amount: 700.0,
      description: "Reward for finding Penny",
      petId: 13,
      locationId: 13,
    },
    {
      amount: 750.0,
      description: "Reward for finding Rosie",
      petId: 14,
      locationId: 14,
    },
    {
      amount: 800.0,
      description: "Reward for finding Maggie",
      petId: 15,
      locationId: 15,
    },
  ],
  comments: [
    { text: "Thank you for helping to find Buddy!", userId: 2, rewardId: 1 },
    { text: "Great job finding Charlie!", userId: 3, rewardId: 2 },
    { text: "So glad Daisy is safe, thanks!", userId: 4, rewardId: 3 },
    { text: "Max is back because of you!", userId: 5, rewardId: 4 },
    { text: "Thank you for finding Bella!", userId: 6, rewardId: 5 },
    { text: "Lucy missed us, thank you!", userId: 7, rewardId: 6 },
    { text: "Molly is home thanks to you!", userId: 8, rewardId: 7 },
    { text: "Bailey is safe, appreciate it!", userId: 9, rewardId: 8 },
    { text: "Stella is back, thank you!", userId: 10, rewardId: 9 },
    { text: "Lola is here, thanks to you!", userId: 11, rewardId: 10 },
    { text: "Happy to have Zoe back!", userId: 12, rewardId: 11 },
    { text: "Ruby is safe, thanks a lot!", userId: 13, rewardId: 12 },
    { text: "Penny is back home, thank you!", userId: 14, rewardId: 13 },
    { text: "Rosie means a lot to us, thanks!", userId: 15, rewardId: 14 },
    { text: "Finding Maggie means the world, thank you!", userId: 16, rewardId: 15 },
  ],
};
