name: "Tag PRs with merge conflicts"

on:
  push:
    paths:
      - '**/*.md'
  pull_request_target:
    types: [synchronized]
    paths:
      - '**/*.md'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: check if prs are dirty
        uses: eps1lon/actions-label-merge-conflict@releases/2.x
        with:
          dirtyLabel: "PR: no se puede revisar, tiene conflictos"
          removeOnDirtyLabel: "PR: lista para revisar"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          commentOnDirty: "⚠️ Esta Pull Request tiene conflictos. Por favor, resuélvelos antes de que podamos evaluar los cambios."
          commentOnClean: "✅ ¡Los conflictos han sido resueltos! Un colaborador revisará pronto la Pull Request."
