name: "Tag PRs with merge conflicts"

on:
  push:
    paths:
      - '**/*.md'
  pull_request_target:
    types: [synchronized]
    paths:
      - '**/*.md'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: check if prs are dirty
        uses: eps1lon/actions-label-merge-conflict@releases/2.x
        with:
          dirtyLabel: "PR: cannot be reviewed, has conflicts"
          removeOnDirtyLabel: "PR: ready for review"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          commentOnDirty: "⚠️ This Pull Request has conflicts. Please resolve them before we can evaluate the changes."
          commentOnClean: "✅ The conflicts have been resolved! A collaborator will review the Pull Request soon."
